{
 "title": "pr_reviewers_service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Business", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "1.1. TOTAL Количество созданных ПРов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "created_prs_total", "legendFormat": "{{city}}" }
   ]
  },
  {
   "title": "2.1. TOTAL Количество созданных команд",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "created_teams_total", "legendFormat": "{{pvz_id}}" }
   ]
  },
  {
   "title": "1.2. RATE[1m] Количество созданных ПРов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "rate(created_prs_total[1m])", "legendFormat": "{{city}}" }
   ]
  },
  {
   "title": "2.2. RATE[1m] Количество созданных команд",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "rate(created_teams_total[1m])", "legendFormat": "{{pvz_id}}" }
   ]
  },
  {
   "title": "3.1. TOTAL Количество созданных юзеров",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "created_users_total", "legendFormat": "{{pvz_id}}" }
   ]
  },
  {
   "title": "3.2. RATE[1m] Количество созданных юзеров",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(created_users_total{}[1m])",
     "legendFormat": "{{pvz_id}}"
    }
   ]
  },
  { "title": "Technical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "1.1. RATE[1m] Количество хитов с распределением по статусу ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(hits_statuses{path!=\"/metrics\"}[1m])",
     "legendFormat": "{{path}}, {{status}}"
    }
   ]
  },
  {
   "title": "2.1. TOTAL Количество хитов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "hits_total{path!=\"/metrics\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "1.2. TOTAL Количество хитов с распределением по статусу ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "hits_statuses{path!=\"/metrics\"}",
     "legendFormat": "{{path}}, {{status}}"
    }
   ]
  },
  {
   "title": "2.2. RATE[1m] Количество хитов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(hits_total{path!=\"/metrics\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "3.1. /api/v1/dummyLogin POST",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by(le) (rate(time_hits_bucket{path=\"/api/v1/dummyLogin\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3.2. /api/v1/statistics/reviewers GET",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by(le) (rate(time_hits_bucket{path=\"/api/v1/statistics/reviewers\", method=\"GET\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3.3. /api/v1/team/get GET",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by(le) (rate(time_hits_bucket{path=\"/api/v1/team/get\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3.4. /api/v1/pullRequest/create POST",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by(le) (rate(time_hits_bucket{path=\"/api/v1/pullRequest/create\", method=\"POST\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3.5. /api/v1/pullRequest/merge POST",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by(le) (rate(time_hits_bucket{path=\"/api/v1/pullRequest/merge\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3.6. /api/v1/pullRequest/reassign POST",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum by(le) (rate(time_hits_bucket{path=\"/api/v1/pullRequest/reassign\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3.7. /api/v1/team/add POST",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum by(le) (rate(time_hits_bucket{path=\"/api/v1/team/add\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3.8. /api/v1/team/deactivateUsers PATCH",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum by(le) (rate(time_hits_bucket{path=\"/api/v1/team/deactivateUsers\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3.9. /api/v1/users/setIsActive POST",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum by(le) (rate(time_hits_bucket{path=\"/api/v1/users/setIsActive\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}