// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package randomizer is a generated GoMock package.
package randomizer

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRandomizer is a mock of Randomizer interface.
type MockRandomizer struct {
	ctrl     *gomock.Controller
	recorder *MockRandomizerMockRecorder
}

// MockRandomizerMockRecorder is the mock recorder for MockRandomizer.
type MockRandomizerMockRecorder struct {
	mock *MockRandomizer
}

// NewMockRandomizer creates a new mock instance.
func NewMockRandomizer(ctrl *gomock.Controller) *MockRandomizer {
	mock := &MockRandomizer{ctrl: ctrl}
	mock.recorder = &MockRandomizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRandomizer) EXPECT() *MockRandomizerMockRecorder {
	return m.recorder
}

// Shuffle mocks base method.
func (m *MockRandomizer) Shuffle(n int, swap func(int, int)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shuffle", n, swap)
}

// Shuffle indicates an expected call of Shuffle.
func (mr *MockRandomizerMockRecorder) Shuffle(n, swap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shuffle", reflect.TypeOf((*MockRandomizer)(nil).Shuffle), n, swap)
}
