// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package pull_requests is a generated GoMock package.
package pull_requests

import (
	context "context"
	pull_requests "pr-reviewers-service/internal/infrastructure/repository/pull_requests"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepositoryPullRequests is a mock of RepositoryPullRequests interface.
type MockRepositoryPullRequests struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryPullRequestsMockRecorder
}

// MockRepositoryPullRequestsMockRecorder is the mock recorder for MockRepositoryPullRequests.
type MockRepositoryPullRequestsMockRecorder struct {
	mock *MockRepositoryPullRequests
}

// NewMockRepositoryPullRequests creates a new mock instance.
func NewMockRepositoryPullRequests(ctrl *gomock.Controller) *MockRepositoryPullRequests {
	mock := &MockRepositoryPullRequests{ctrl: ctrl}
	mock.recorder = &MockRepositoryPullRequestsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryPullRequests) EXPECT() *MockRepositoryPullRequestsMockRecorder {
	return m.recorder
}

// GetPullRequestByID mocks base method.
func (m *MockRepositoryPullRequests) GetPullRequestByID(ctx context.Context, prID uuid.UUID) (*pull_requests.PullRequestOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestByID", ctx, prID)
	ret0, _ := ret[0].(*pull_requests.PullRequestOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestByID indicates an expected call of GetPullRequestByID.
func (mr *MockRepositoryPullRequestsMockRecorder) GetPullRequestByID(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestByID", reflect.TypeOf((*MockRepositoryPullRequests)(nil).GetPullRequestByID), ctx, prID)
}

// GetPullRequestsByPrIDs mocks base method.
func (m *MockRepositoryPullRequests) GetPullRequestsByPrIDs(ctx context.Context, prIDs []uuid.UUID) (*[]pull_requests.PullRequestOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestsByPrIDs", ctx, prIDs)
	ret0, _ := ret[0].(*[]pull_requests.PullRequestOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestsByPrIDs indicates an expected call of GetPullRequestsByPrIDs.
func (mr *MockRepositoryPullRequestsMockRecorder) GetPullRequestsByPrIDs(ctx, prIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestsByPrIDs", reflect.TypeOf((*MockRepositoryPullRequests)(nil).GetPullRequestsByPrIDs), ctx, prIDs)
}

// MarkPullRequestMergedByID mocks base method.
func (m *MockRepositoryPullRequests) MarkPullRequestMergedByID(ctx context.Context, prID uuid.UUID) (*pull_requests.PullRequestOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPullRequestMergedByID", ctx, prID)
	ret0, _ := ret[0].(*pull_requests.PullRequestOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPullRequestMergedByID indicates an expected call of MarkPullRequestMergedByID.
func (mr *MockRepositoryPullRequestsMockRecorder) MarkPullRequestMergedByID(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPullRequestMergedByID", reflect.TypeOf((*MockRepositoryPullRequests)(nil).MarkPullRequestMergedByID), ctx, prID)
}

// SavePullRequest mocks base method.
func (m *MockRepositoryPullRequests) SavePullRequest(ctx context.Context, pr pull_requests.PullRequestIn) (*pull_requests.PullRequestOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePullRequest", ctx, pr)
	ret0, _ := ret[0].(*pull_requests.PullRequestOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SavePullRequest indicates an expected call of SavePullRequest.
func (mr *MockRepositoryPullRequestsMockRecorder) SavePullRequest(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePullRequest", reflect.TypeOf((*MockRepositoryPullRequests)(nil).SavePullRequest), ctx, pr)
}
