// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package users is a generated GoMock package.
package users

import (
	context "context"
	users "pr-reviewers-service/internal/infrastructure/repository/users"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepositoryUsers is a mock of RepositoryUsers interface.
type MockRepositoryUsers struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryUsersMockRecorder
}

// MockRepositoryUsersMockRecorder is the mock recorder for MockRepositoryUsers.
type MockRepositoryUsersMockRecorder struct {
	mock *MockRepositoryUsers
}

// NewMockRepositoryUsers creates a new mock instance.
func NewMockRepositoryUsers(ctrl *gomock.Controller) *MockRepositoryUsers {
	mock := &MockRepositoryUsers{ctrl: ctrl}
	mock.recorder = &MockRepositoryUsersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryUsers) EXPECT() *MockRepositoryUsersMockRecorder {
	return m.recorder
}

// GetActiveUsersByTeamID mocks base method.
func (m *MockRepositoryUsers) GetActiveUsersByTeamID(ctx context.Context, teamID uuid.UUID) (*[]users.UserOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUsersByTeamID", ctx, teamID)
	ret0, _ := ret[0].(*[]users.UserOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUsersByTeamID indicates an expected call of GetActiveUsersByTeamID.
func (mr *MockRepositoryUsersMockRecorder) GetActiveUsersByTeamID(ctx, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUsersByTeamID", reflect.TypeOf((*MockRepositoryUsers)(nil).GetActiveUsersByTeamID), ctx, teamID)
}

// GetUserByID mocks base method.
func (m *MockRepositoryUsers) GetUserByID(ctx context.Context, userId uuid.UUID) (*users.UserOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userId)
	ret0, _ := ret[0].(*users.UserOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryUsersMockRecorder) GetUserByID(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepositoryUsers)(nil).GetUserByID), ctx, userId)
}

// GetUsersByIDs mocks base method.
func (m *MockRepositoryUsers) GetUsersByIDs(ctx context.Context, userIds []uuid.UUID) (*[]users.UserOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByIDs", ctx, userIds)
	ret0, _ := ret[0].(*[]users.UserOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByIDs indicates an expected call of GetUsersByIDs.
func (mr *MockRepositoryUsersMockRecorder) GetUsersByIDs(ctx, userIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByIDs", reflect.TypeOf((*MockRepositoryUsers)(nil).GetUsersByIDs), ctx, userIds)
}

// GetUsersByTeamID mocks base method.
func (m *MockRepositoryUsers) GetUsersByTeamID(ctx context.Context, teamID uuid.UUID) (*[]users.UserOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByTeamID", ctx, teamID)
	ret0, _ := ret[0].(*[]users.UserOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByTeamID indicates an expected call of GetUsersByTeamID.
func (mr *MockRepositoryUsersMockRecorder) GetUsersByTeamID(ctx, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByTeamID", reflect.TypeOf((*MockRepositoryUsers)(nil).GetUsersByTeamID), ctx, teamID)
}

// SaveUsersBatch mocks base method.
func (m *MockRepositoryUsers) SaveUsersBatch(ctx context.Context, urs []users.UserIn) (*[]users.UserOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUsersBatch", ctx, urs)
	ret0, _ := ret[0].(*[]users.UserOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUsersBatch indicates an expected call of SaveUsersBatch.
func (mr *MockRepositoryUsersMockRecorder) SaveUsersBatch(ctx, urs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUsersBatch", reflect.TypeOf((*MockRepositoryUsers)(nil).SaveUsersBatch), ctx, urs)
}

// UpdateUser mocks base method.
func (m *MockRepositoryUsers) UpdateUser(ctx context.Context, user users.UserIn) (*users.UserOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(*users.UserOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockRepositoryUsersMockRecorder) UpdateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockRepositoryUsers)(nil).UpdateUser), ctx, user)
}

// UpdateUsersBatch mocks base method.
func (m *MockRepositoryUsers) UpdateUsersBatch(ctx context.Context, urs []users.UserIn) (*[]users.UserOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsersBatch", ctx, urs)
	ret0, _ := ret[0].(*[]users.UserOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUsersBatch indicates an expected call of UpdateUsersBatch.
func (mr *MockRepositoryUsersMockRecorder) UpdateUsersBatch(ctx, urs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsersBatch", reflect.TypeOf((*MockRepositoryUsers)(nil).UpdateUsersBatch), ctx, urs)
}
