// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package pr_statuses is a generated GoMock package.
package pr_statuses

import (
	context "context"
	pr_statuses "pr-reviewers-service/internal/infrastructure/repository/pr_statuses"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepositoryPrStatuses is a mock of RepositoryPrStatuses interface.
type MockRepositoryPrStatuses struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryPrStatusesMockRecorder
}

// MockRepositoryPrStatusesMockRecorder is the mock recorder for MockRepositoryPrStatuses.
type MockRepositoryPrStatusesMockRecorder struct {
	mock *MockRepositoryPrStatuses
}

// NewMockRepositoryPrStatuses creates a new mock instance.
func NewMockRepositoryPrStatuses(ctrl *gomock.Controller) *MockRepositoryPrStatuses {
	mock := &MockRepositoryPrStatuses{ctrl: ctrl}
	mock.recorder = &MockRepositoryPrStatusesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryPrStatuses) EXPECT() *MockRepositoryPrStatusesMockRecorder {
	return m.recorder
}

// GetPRStatusByID mocks base method.
func (m *MockRepositoryPrStatuses) GetPRStatusByID(ctx context.Context, status pr_statuses.PRStatusIn) (*pr_statuses.PRStatusOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRStatusByID", ctx, status)
	ret0, _ := ret[0].(*pr_statuses.PRStatusOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRStatusByID indicates an expected call of GetPRStatusByID.
func (mr *MockRepositoryPrStatusesMockRecorder) GetPRStatusByID(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRStatusByID", reflect.TypeOf((*MockRepositoryPrStatuses)(nil).GetPRStatusByID), ctx, status)
}

// GetPRStatusesByIDs mocks base method.
func (m *MockRepositoryPrStatuses) GetPRStatusesByIDs(ctx context.Context, statusIDs []uuid.UUID) (*[]pr_statuses.PRStatusOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRStatusesByIDs", ctx, statusIDs)
	ret0, _ := ret[0].(*[]pr_statuses.PRStatusOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRStatusesByIDs indicates an expected call of GetPRStatusesByIDs.
func (mr *MockRepositoryPrStatusesMockRecorder) GetPRStatusesByIDs(ctx, statusIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRStatusesByIDs", reflect.TypeOf((*MockRepositoryPrStatuses)(nil).GetPRStatusesByIDs), ctx, statusIDs)
}

// SavePRStatus mocks base method.
func (m *MockRepositoryPrStatuses) SavePRStatus(ctx context.Context, status pr_statuses.PRStatusIn) (*pr_statuses.PRStatusOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePRStatus", ctx, status)
	ret0, _ := ret[0].(*pr_statuses.PRStatusOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SavePRStatus indicates an expected call of SavePRStatus.
func (mr *MockRepositoryPrStatusesMockRecorder) SavePRStatus(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePRStatus", reflect.TypeOf((*MockRepositoryPrStatuses)(nil).SavePRStatus), ctx, status)
}

// UpdatePRStatusByID mocks base method.
func (m *MockRepositoryPrStatuses) UpdatePRStatusByID(ctx context.Context, status pr_statuses.PRStatusIn) (*pr_statuses.PRStatusOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePRStatusByID", ctx, status)
	ret0, _ := ret[0].(*pr_statuses.PRStatusOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePRStatusByID indicates an expected call of UpdatePRStatusByID.
func (mr *MockRepositoryPrStatusesMockRecorder) UpdatePRStatusByID(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePRStatusByID", reflect.TypeOf((*MockRepositoryPrStatuses)(nil).UpdatePRStatusByID), ctx, status)
}
