// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package teams is a generated GoMock package.
package teams

import (
	context "context"
	teams "pr-reviewers-service/internal/infrastructure/repository/teams"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepositoryTeams is a mock of RepositoryTeams interface.
type MockRepositoryTeams struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryTeamsMockRecorder
}

// MockRepositoryTeamsMockRecorder is the mock recorder for MockRepositoryTeams.
type MockRepositoryTeamsMockRecorder struct {
	mock *MockRepositoryTeams
}

// NewMockRepositoryTeams creates a new mock instance.
func NewMockRepositoryTeams(ctrl *gomock.Controller) *MockRepositoryTeams {
	mock := &MockRepositoryTeams{ctrl: ctrl}
	mock.recorder = &MockRepositoryTeamsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryTeams) EXPECT() *MockRepositoryTeamsMockRecorder {
	return m.recorder
}

// GetTeamByID mocks base method.
func (m *MockRepositoryTeams) GetTeamByID(ctx context.Context, team uuid.UUID) (*teams.TeamOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByID", ctx, team)
	ret0, _ := ret[0].(*teams.TeamOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByID indicates an expected call of GetTeamByID.
func (mr *MockRepositoryTeamsMockRecorder) GetTeamByID(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByID", reflect.TypeOf((*MockRepositoryTeams)(nil).GetTeamByID), ctx, team)
}

// GetTeamByName mocks base method.
func (m *MockRepositoryTeams) GetTeamByName(ctx context.Context, name string) (*teams.TeamOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByName", ctx, name)
	ret0, _ := ret[0].(*teams.TeamOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByName indicates an expected call of GetTeamByName.
func (mr *MockRepositoryTeamsMockRecorder) GetTeamByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByName", reflect.TypeOf((*MockRepositoryTeams)(nil).GetTeamByName), ctx, name)
}

// SaveTeam mocks base method.
func (m *MockRepositoryTeams) SaveTeam(ctx context.Context, team teams.TeamIn) (*teams.TeamOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTeam", ctx, team)
	ret0, _ := ret[0].(*teams.TeamOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTeam indicates an expected call of SaveTeam.
func (mr *MockRepositoryTeamsMockRecorder) SaveTeam(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTeam", reflect.TypeOf((*MockRepositoryTeams)(nil).SaveTeam), ctx, team)
}
