// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package pr_reviewers is a generated GoMock package.
package pr_reviewers

import (
	context "context"
	pr_reviewers "pr-reviewers-service/internal/infrastructure/repository/pr_reviewers"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepositoryPrReviewers is a mock of RepositoryPrReviewers interface.
type MockRepositoryPrReviewers struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryPrReviewersMockRecorder
}

// MockRepositoryPrReviewersMockRecorder is the mock recorder for MockRepositoryPrReviewers.
type MockRepositoryPrReviewersMockRecorder struct {
	mock *MockRepositoryPrReviewers
}

// NewMockRepositoryPrReviewers creates a new mock instance.
func NewMockRepositoryPrReviewers(ctrl *gomock.Controller) *MockRepositoryPrReviewers {
	mock := &MockRepositoryPrReviewers{ctrl: ctrl}
	mock.recorder = &MockRepositoryPrReviewersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryPrReviewers) EXPECT() *MockRepositoryPrReviewersMockRecorder {
	return m.recorder
}

// DeletePRReviewerByPRAndReviewer mocks base method.
func (m *MockRepositoryPrReviewers) DeletePRReviewerByPRAndReviewer(ctx context.Context, prID, reviewerID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePRReviewerByPRAndReviewer", ctx, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePRReviewerByPRAndReviewer indicates an expected call of DeletePRReviewerByPRAndReviewer.
func (mr *MockRepositoryPrReviewersMockRecorder) DeletePRReviewerByPRAndReviewer(ctx, prID, reviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePRReviewerByPRAndReviewer", reflect.TypeOf((*MockRepositoryPrReviewers)(nil).DeletePRReviewerByPRAndReviewer), ctx, prID, reviewerID)
}

// GetAllPRReviewers mocks base method.
func (m *MockRepositoryPrReviewers) GetAllPRReviewers(ctx context.Context) (*[]pr_reviewers.PrReviewerOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPRReviewers", ctx)
	ret0, _ := ret[0].(*[]pr_reviewers.PrReviewerOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPRReviewers indicates an expected call of GetAllPRReviewers.
func (mr *MockRepositoryPrReviewersMockRecorder) GetAllPRReviewers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPRReviewers", reflect.TypeOf((*MockRepositoryPrReviewers)(nil).GetAllPRReviewers), ctx)
}

// GetPRReviewersByPRID mocks base method.
func (m *MockRepositoryPrReviewers) GetPRReviewersByPRID(ctx context.Context, prID uuid.UUID) (*[]pr_reviewers.PrReviewerOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRReviewersByPRID", ctx, prID)
	ret0, _ := ret[0].(*[]pr_reviewers.PrReviewerOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRReviewersByPRID indicates an expected call of GetPRReviewersByPRID.
func (mr *MockRepositoryPrReviewersMockRecorder) GetPRReviewersByPRID(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRReviewersByPRID", reflect.TypeOf((*MockRepositoryPrReviewers)(nil).GetPRReviewersByPRID), ctx, prID)
}

// GetPRReviewersByReviewerID mocks base method.
func (m *MockRepositoryPrReviewers) GetPRReviewersByReviewerID(ctx context.Context, reviewerID uuid.UUID) (*[]pr_reviewers.PrReviewerOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRReviewersByReviewerID", ctx, reviewerID)
	ret0, _ := ret[0].(*[]pr_reviewers.PrReviewerOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRReviewersByReviewerID indicates an expected call of GetPRReviewersByReviewerID.
func (mr *MockRepositoryPrReviewersMockRecorder) GetPRReviewersByReviewerID(ctx, reviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRReviewersByReviewerID", reflect.TypeOf((*MockRepositoryPrReviewers)(nil).GetPRReviewersByReviewerID), ctx, reviewerID)
}

// GetPRReviewersByReviewerIDs mocks base method.
func (m *MockRepositoryPrReviewers) GetPRReviewersByReviewerIDs(ctx context.Context, reviewerIDs []uuid.UUID) (*[]pr_reviewers.PrReviewerOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRReviewersByReviewerIDs", ctx, reviewerIDs)
	ret0, _ := ret[0].(*[]pr_reviewers.PrReviewerOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRReviewersByReviewerIDs indicates an expected call of GetPRReviewersByReviewerIDs.
func (mr *MockRepositoryPrReviewersMockRecorder) GetPRReviewersByReviewerIDs(ctx, reviewerIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRReviewersByReviewerIDs", reflect.TypeOf((*MockRepositoryPrReviewers)(nil).GetPRReviewersByReviewerIDs), ctx, reviewerIDs)
}

// SavePRReviewer mocks base method.
func (m *MockRepositoryPrReviewers) SavePRReviewer(ctx context.Context, reviewer pr_reviewers.PrReviewerIn) (*pr_reviewers.PrReviewerOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePRReviewer", ctx, reviewer)
	ret0, _ := ret[0].(*pr_reviewers.PrReviewerOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SavePRReviewer indicates an expected call of SavePRReviewer.
func (mr *MockRepositoryPrReviewersMockRecorder) SavePRReviewer(ctx, reviewer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePRReviewer", reflect.TypeOf((*MockRepositoryPrReviewers)(nil).SavePRReviewer), ctx, reviewer)
}
